name: Build and Deploy

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Get a newImageURL
        id: newImageURL
        env:
          REGISTRY: ${{ secrets.DIGITALOCEAN_CONTAINER_REGISTRY }}
        run: 'echo "VALUE=$(.github/workflows/genNewImageUrl.sh)" >> $GITHUB_OUTPUT'

      - name: Build image 
        run: docker build -t ${{ steps.newImageURL.outputs.VALUE }} .
      
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry
        run: docker push ${{ steps.newImageURL.outputs.VALUE }}

      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop bankeer-bot
            docker rm bankeer-bot
            docker run --name bankeer-bot -dit \
                  #  -v /host/path/to/certs:/certs
                   -v ${{ secrets.CERTS_LOCATION }}:/certs
                   -e BANK_TOKEN=${{ secrets.BANK_TOKEN }}\
                   -e BANK_ACCOUNT_TOKEN=${{ secrets.BANK_ACCOUNT_TOKEN }}\
                   -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}\ 
                   -e ALLOWED_USERS=${{ secrets.ALLOWED_USERS }}\
                   -e PUBLIC_HOST_ADDRESS=${{ secrets.PUBLIC_HOST_ADDRESS }}\
                   -p 433:8443
                   ${{ steps.newImageURL.outputs.VALUE }}